#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use marvin255\fias\cli\InstallCommand;
use marvin255\fias\cli\UpdateCommand;

require __DIR__ . '/../vendor/autoload.php';

$application = new Application;

$application->add(new InstallCommand);
$application->add(new UpdateCommand);

$application->run();
