language: php
services:
  - mysql
sudo: false
php:
  - 7.0
  - 7.1
  - 7.2
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - mysql -e 'DROP DATABASE IF EXISTS fias;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS fias;'
  - echo "<?php define('PHPUNIT_PDO_DSN', 'mysql:host=localhost;dbname=fias;charset=UTF8'); define('PHPUNIT_PDO_USER', 'travis'); define('PHPUNIT_PDO_PASSWORD', ''); " > tests/.env.bootstrap.php
script:
  - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no
  - vendor/bin/phpcpd src
  - vendor/bin/psalm
  - vendor/bin/phpunit -c phpunit.xml.dist
